import feedparser
import datetime
import os
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from deep_translator import GoogleTranslator

# ── 新闻来源（RSS） ────────────────────────────────────────────────
FEEDS = {
    "🌍 国际政治 / World Politics": [
        "http://feeds.bbci.co.uk/news/world/rss.xml",
        "https://feeds.reuters.com/reuters/worldNews",
    ],
    "💰 经济财经 / Economy & Finance": [
        "https://feeds.reuters.com/reuters/businessNews",
        "https://feeds.bbci.co.uk/news/business/rss.xml",
    ],
    "🔬 科技科学 / Technology & Science": [
        "https://feeds.bbci.co.uk/news/technology/rss.xml",
        "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    ],
    "🎭 文化社会 / Culture & Society": [
        "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
        "https://feeds.reuters.com/reuters/lifestyle",
    ],
    "⚽ 体育 / Sports": [
        "https://feeds.bbci.co.uk/sport/rss.xml",
    ],
}

ARTICLES_PER_SECTION = 4  # 每个板块抓取条数


def fetch_articles(urls, limit):
    articles = []
    for url in urls:
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                if len(articles) >= limit:
                    break
                title = entry.get("title", "").strip()
                summary = entry.get("summary", entry.get("description", "")).strip()
                # 去除 HTML 标签
                import re
                summary = re.sub(r"<[^>]+>", "", summary)
                summary = summary[:300]  # 截断过长摘要
                if title:
                    articles.append({"title": title, "summary": summary})
        except Exception as e:
            print(f"  [警告] 抓取 {url} 失败: {e}")
        if len(articles) >= limit:
            break
    return articles[:limit]


def translate_to_chinese(text):
    if not text:
        return ""
    try:
        translator = GoogleTranslator(source="auto", target="zh-CN")
        # Google 翻译单次上限约 5000 字符
        if len(text) > 4500:
            text = text[:4500]
        return translator.translate(text)
    except Exception as e:
        print(f"  [警告] 翻译失败: {e}")
        return text


# ── 生成 Word 文档 ────────────────────────────────────────────────
def build_document(sections_data, week_str):
    doc = Document()

    # 页面边距
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)

    # 标题
    title = doc.add_heading("", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(f"每周全球时事新闻简报")
    run.font.size = Pt(22)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run(f"Weekly Global News Briefing  ·  {week_str}")
    sub_run.font.size = Pt(11)
    sub_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    doc.add_paragraph()

    for section_name, articles in sections_data.items():
        # 板块标题
        h = doc.add_heading("", level=1)
        h_run = h.add_run(section_name)
        h_run.font.size = Pt(14)
        h_run.font.bold = True
        h_run.font.color.rgb = RGBColor(0x2E, 0x74, 0xB5)

        if not articles:
            doc.add_paragraph("（本周暂无相关新闻 / No articles available this week）")
            continue

        for i, art in enumerate(articles, 1):
            # 英文标题
            en_title_para = doc.add_paragraph()
            en_run = en_title_para.add_run(f"{i}. {art['en_title']}")
            en_run.font.bold = True
            en_run.font.size = Pt(11)

            # 中文标题
            cn_title_para = doc.add_paragraph()
            cn_run = cn_title_para.add_run(f"   {art['cn_title']}")
            cn_run.font.bold = True
            cn_run.font.size = Pt(11)
            cn_run.font.color.rgb = RGBColor(0x1F, 0x49, 0x7D)

            # 英文摘要
            if art["en_summary"]:
                en_sum = doc.add_paragraph(style="List Bullet")
                en_sum_run = en_sum.add_run(art["en_summary"])
                en_sum_run.font.size = Pt(10)
                en_sum_run.font.color.rgb = RGBColor(0x40, 0x40, 0x40)

            # 中文摘要
            if art["cn_summary"]:
                cn_sum = doc.add_paragraph(style="List Bullet")
                cn_sum_run = cn_sum.add_run(art["cn_summary"])
                cn_sum_run.font.size = Pt(10)
                cn_sum_run.font.color.rgb = RGBColor(0x40, 0x40, 0x40)

            doc.add_paragraph()

    # 页脚说明
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.add_run(
        "新闻来源：BBC News · Reuters  |  自动生成 · Auto-generated by WeeklyNews Bot"
    )
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)

    return doc


# ── 主流程 ────────────────────────────────────────────────────────
def main():
    today = datetime.date.today()
    week_str = today.strftime("%Y 年第 %W 周  |  Week %W, %Y")
    filename = f"WeeklyNews_{today.strftime('%Y-%m-%d')}.docx"
    output_dir = "reports"
    os.makedirs(output_dir, exist_ok=True)

    print(f"📰 开始抓取新闻 ({today}) ...")
    sections_data = {}

    for section_name, urls in FEEDS.items():
        print(f"\n  板块: {section_name}")
        raw_articles = fetch_articles(urls, ARTICLES_PER_SECTION)
        processed = []
        for art in raw_articles:
            print(f"    翻译: {art['title'][:50]}...")
            processed.append({
                "en_title": art["title"],
                "cn_title": translate_to_chinese(art["title"]),
                "en_summary": art["summary"],
                "cn_summary": translate_to_chinese(art["summary"]) if art["summary"] else "",
            })
        sections_data[section_name] = processed

    print(f"\n📄 生成 Word 文档...")
    doc = build_document(sections_data, week_str)
    output_path = os.path.join(output_dir, filename)
    doc.save(output_path)
    print(f"✅ 已保存: {output_path}")


if __name__ == "__main__":
    main()
